config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" } 

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  namespace :admin do
    resources :products, only: [:index]
    resources :coupons
    resources :promotions
    resources :users, only: [:index, :destroy]
    resource :dashboard, controller: :dashboard, only: [:show]
  end

  namespace :seller do 
    resources :products do
      resources :comments
      collection do
        get :autocomplete
      end 
    end
  end

  resources :products, only: [:index, :show] do  
    collection do
      get :autocomplete
    end 
    resources :comments
  end

  resources :users
  resource :cart, controller: :cart, only: [:show, :destroy]  
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:index] do 
    collection do 
      post :apply_coupon, as: :coupon
      get :pending_order, as: :pending
    end
  end
  resources :charges, only: [:create]
  
  root to: 'products#index'
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController
    def show
      @user_count = User.count
      @product_count = Product.count
      @promotion_count = Promotion.count
      @coupon_count = Coupon.count
    end
  end
end

app/views/admin/dashboard/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col">
      <div class="counter">
        <i class="fa fa-users fa-2x"></i>
        <h2 class="timer count-title count-number" data-to=<%= @user_count %> data-speed="1500"></h2>
        <p class="count-text ">Total Users</p>
      </div>
    </div>
    <div class="col">
      <div class="counter">
        <i class="fa fa-archive fa-2x"></i>
        <h2 class="timer count-title count-number" data-to=<%= @product_count %> data-speed="1500"></h2>
        <p class="count-text ">Total Products</p>
      </div>
    </div>
    <div class="col">
      <div class="counter">
        <i class="fa fa-tag fa-2x"></i>
        <h2 class="timer count-title count-number" data-to=<%= @coupon_count %> data-speed="1500"></h2>
        <p class="count-text ">Total Coupons</p>
      </div>
    </div>
    <div class="col">
      <div class="counter">
        <i class="fa fa-bullhorn fa-2x"></i>
        <h2 class="timer count-title count-number" data-to=<%= @promotion_count %> data-speed="1500"></h2>
        <p class="count-text ">Total Promotions</p>
      </div>
    </div>
  </div>
  <br>
  <div class="row text-center">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-3">
      <div class="counter">
        <i class="fa fa-shopping-cart fa-2x"></i>
        <h2 class="timer count-title count-number" data-to=<%= @user_count %> data-speed="1500"></h2>
        <p class="count-text ">Products Sold</p>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="counter">
        <i class="fa fa-money fa-2x"></i>
        <h2 class="timer count-title count-number" data-to=<%= @user_count %> data-speed="1500"></h2>
        <p class="count-text ">Total Business</p>
      </div>
    </div>
    <div class="col-sm-3">
    </div>
  </div>
  <div>
    <p class="text-center admin-actions">
    <%= link_to "Products", products_path, class: "btn btn-success"%>
    <%= link_to "Manage Promotions", admin_promotions_path, class: "btn btn-danger"%>
    <%= link_to "Manage Coupons", admin_coupons_path, class: "btn btn-info"%>
    <%= link_to "Manage Users", admin_users_path, class: "btn btn-warning"%>
    </p>
  </div>
</div>