config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" } 

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  namespace :admin do
    resources :products, only: [:index]
    resources :coupons
    resources :promotions
    resources :users, only: [:index, :destroy]
    resource :dashboard, controller: :dashboard, only: [:show]
  end

  namespace :seller do 
    resources :products do
      resources :comments
      collection do
        get :autocomplete
      end 
    end
  end

  resources :products, only: [:index, :show] do  
    collection do
      get :autocomplete
    end 
    resources :comments
  end

  resources :users
  resource :cart, controller: :cart, only: [:show, :destroy]  
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:index] do 
    collection do 
      post :apply_coupon, as: :coupon
      get :pending_order, as: :pending
    end
  end
  resources :charges, only: [:create]
  
  root to: 'products#index'
end

app/views/partials/_navbar.html.erb
<div class="authLinksContainer">
  <div class="authLinks">
    <% if !user_signed_in? %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% elsif !current_user.guest?%>
      <%= render partial: "partials/user_profile" %>
    <% end %>
  </div>
</div>
<nav class="navbar navbar-expand-lg no-radius-border">
  <div class="collapse navbar-collapse" id="navbar" style="display: flex; justify-content: center;">
    <%= link_to image_tag("logo.png", class:"logo"), root_path %>
    <%= render 'partials/search' %>
    <% if current_or_guest_user.has_role?(:buyer) %>
      <%= link_to "", cart_path, class: "fa fa-shopping-cart cart-icon" %>
    <% end %>
  </div>
</nav>

app/views/partials/_search.html.erb
<%= form_tag(products_path, method: :get, id: 'product-search', autocomplete: :off) do %>
  <%= text_field_tag :query, params[:query], id:'autocomplete', class: 'search-bar', placeholder: "Search Products..."%>
  <%= submit_tag "Search", class: "fas fa-search search-btn" %>
<% end %>

app/views/partials/_user_profile.html.erb
<div class="profileLink">
  <div class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username.capitalize + " "%><%= image_tag user_image(current_user) , class: "img-rounded user-avatar-sm"%></a>
    <ul class="dropdown-menu">
      <% if current_user.has_role?(:admin) %>
        <li><a href=<%= admin_dashboard_path%> >Dashboard <span class="glyphicon glyphicon-cog pull-right"></span></a></li>
        <li class="divider"></li>
      <% end %>
      <li><a href=<%= user_path(current_user)%> >Profile <span class="glyphicon glyphicon-cog pull-right"></span></a></li>
      <li class="divider"></li>
      <li ><p><%= link_to("Sign Out", destroy_user_session_path, method: :delete)%><span class="glyphicon glyphicon-log-out pull-right"></span></p></li>
    </ul>
  </div>
</div>