config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" } 

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  namespace :admin do
    resources :products, only: [:index]
    resources :coupons
    resources :promotions
    resources :users, only: [:index, :destroy]
    resource :dashboard, controller: :dashboard, only: [:show]
  end

  namespace :seller do 
    resources :products do
      resources :comments
      collection do
        get :autocomplete
      end 
    end
  end

  resources :products, only: [:index, :show] do  
    collection do
      get :autocomplete
    end 
    resources :comments
  end

  resources :users
  resource :cart, controller: :cart, only: [:show, :destroy]  
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:index] do 
    collection do 
      post :apply_coupon, as: :coupon
      get :pending_order, as: :pending
    end
  end
  resources :charges, only: [:create]
  
  root to: 'products#index'
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_one_attached :image 

  validates :title, :expire_at, presence: true

  scope :active, -> { where("expire_at > ? ", Date.current) }
end

app/controllers/admin/promotions_controller.rb
module Admin
  class PromotionsController < BaseController
    before_action :set_promotion, only: [:edit,:update, :show, :destroy]
    def index
      @promotions = Promotion.active
    end

    def new 
      @promotion = Promotion.new
    end

    def create
      if promotion_params[:expire_at] < DateTime.now
        redirect_to new_admin_promotion_path, alert: "Invalid Expiry Date" 
        return
      end
      promotion = Promotion.new({title: promotion_params[:title], expire_at: promotion_params[:expire_at], image: promotion_params[:image]})
      promotion.save

      redirect_to admin_promotions_path
    end

    def update
      @promotion.update!(promotion_params)
    end

    def destroy
      @promotion.destroy
      redirect_to admin_promotions_path
    end

    private
      def promotion_params
        params.require(:promotion).permit(:title, :image, :expire_at)
      end

      def set_promotion
        @promotion = Promotion.find_by(id: params[:id])
      end
  end
end

app/helpers/admin/promotions_helper.rb
module Admin::PromotionsHelper
  def promo_image(promo)
    if promo && promo.image.attached?
        promo.image
    else
        image_path('user.png')
    end
  end
end

app/views/admin/promotions/_form.html.erb
<div class="container" style="width:30vw !important">
  <h3 class="text-center"><%= message %></h3>
  <%= form_for [:admin, @promotion] do |f| %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, autofocus: true, required: true, class: "form-group form-control form-control-sm bg-light" %>
    </div>

    <div class="field">
      <%= f.label :expire_at %><br />
      <%= f.text_field :expire_at, type: :date, required: true, class: "form-group form-control form-control-sm bg-light" %>
    </div>

    <div class="field">
      <%= f.label :attachements %><br />
      <%= f.file_field :image, required: true, class: "btn btn-light" %>
    </div>
    <br>
    <div class="field text-center">
      <%= f.submit class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/promotions/edit.html.erb
<%= render 'form', { message: 'Edit Promotion' } %>

app/views/admin/promotions/index.html.erb
<h1 class="text-center">Promotional Charts</h1>
<p class="text-center"><%= link_to 'Add New Promotion', new_admin_promotion_path, class: "btn btn-warning" %></p>
<br>
<table id="coupon_datatable" class="table table-hover">
  <thead>
    <tr>
      <th>Index</th>
      <th>Title</th>
      <th>Thumbnail</th>     
      <th>Expires At</th>     
      <th>Actions</th>     

    </tr>
  </thead>
  <tbody>
    <% @promotions.each_with_index do |promo, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%=promo.title%></td>
        <td><%= image_tag(promo_image(promo), class: "promotion-list-image")%></td>
        <td><%=promo.expire_at%></td>
        <td>
          <%= link_to "Edit", edit_admin_promotion_path(promo), class: "btn btn-success"%> 
          <%= link_to "Delete", admin_promotion_path(promo), method: :delete, data:{ confirm: "Are you Sure?"}, class: "btn btn-danger"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/promotions/new.html.erb
<%= render 'form', { message: 'New Promotion' } %>