config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" } 

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  namespace :admin do
    resources :products, only: [:index]
    resources :coupons
    resources :promotions
    resources :users, only: [:index, :destroy]
    resource :dashboard, controller: :dashboard, only: [:show]
  end

  namespace :seller do 
    resources :products do
      resources :comments
      collection do
        get :autocomplete
      end 
    end
  end

  resources :products, only: [:index, :show] do  
    collection do
      get :autocomplete
    end 
    resources :comments
  end

  resources :users
  resource :cart, controller: :cart, only: [:show, :destroy]  
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:index] do 
    collection do 
      post :apply_coupon, as: :coupon
      get :pending_order, as: :pending
    end
  end
  resources :charges, only: [:create]
  
  root to: 'products#index'
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  scope :active, -> { where("expire_at > ? ", Date.current) }
  
  has_many :orders
end

app/controllers/admin/coupons_controller.rb
module Admin
  class CouponsController < BaseController
    before_action :set_coupon, only: [:edit, :update, :destroy]
    
    def index
      @coupons = Coupon.active
    end

    def new
      @coupon = Coupon.new
    end

    def create
      Coupon.create!(coupon_params)
      redirect_to admin_coupons_path
    end

    def edit; end

    def update
      @coupon.update(coupon_params)
      redirect_to admin_coupons_path
    end

    def destroy
      @coupon.destroy
      redirect_to admin_coupons_path
    end

    private
    def coupon_params
      params.require(:coupon).permit(:title, :discount, :expire_at)
    end

    def set_coupon
      @coupon = Coupon.find(params[:id])
    end
  end
end

app/views/admin/coupons/_form.html.erb
<div class="container" style="width:30vw !important">
  <h3 class="text-center"><%= message %></h3>
  <%= form_for [:admin, @coupon] do |f| %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, autofocus: true, required: true, class: "form-group form-control form-control-sm bg-light" %>
    </div>

    <div class="field">
      <%= f.label :expire_at %><br />
      <%= f.text_field :expire_at, type: :date, required: true, class: "form-group form-control form-control-sm bg-light" %>
    </div>

    <div class="field">
      <%= f.label :discount %><br />
      <%= f.text_field :discount, type: :decimal, required: true, class: "form-group form-control form-control-sm bg-light", placeholder: "Enter discount in percentage" %>
    </div>

    <div class="field text-center">
      <%= f.submit class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/coupons/edit.html.erb
<%= render 'form', { message: 'Edit Coupon for Discount' } %>

app/views/admin/coupons/index.html.erb
<h1 class="text-center">Discount Coupons</h1>
<p class="text-center"><%= link_to 'Add New Coupon', new_admin_coupon_path, class: "btn btn-warning" %></p>
<br>
<table id="coupon_datatable" class="table table-hover">
  <thead>
    <tr>
      <th>Index</th>
      <th>Title</th>
      <th>Discount</th>     
      <th>Expires At</th>     
      <th>Actions</th>     

    </tr>
  </thead>
  <tbody>
    <% @coupons.each_with_index do |coupon, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%=coupon.title%></td>
        <td><%=coupon.discount%> %</td>
        <td><%=coupon.expire_at%></td>
        <td>
          <%= link_to "Edit", edit_admin_coupon_path(coupon), class: "btn btn-success"%> 
          <%= link_to "Delete", admin_coupon_path(coupon), method: :delete, data:{ confirm: "Are you Sure?"}, class: "btn btn-danger"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/coupons/new.html.erb
<%= render 'form', { message: 'New Coupon for Discount' } %>